import Head from 'next/head'
import React from 'react'
import Abbtus from './Abbtus'

export default function Aboutus() {
  return (
    <div>
      <Head>
        <title>Aboutus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Abbtus />
    </div>
  )
}
